image: deavidsedice/pineboo-build:latest-devel
variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: none
  GIT_SUBMODULE_STRATEGY: none
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
# variables:
#   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

stages:
    - test
    - deploy

before_script:
    - python3 -V | ts # Print out python version for debugging
    - pip3 install -r requirements.txt | ts
    # - pip install virtualenv
    # - virtualenv venv
    # - source venv/bin/activate

# Spawn 2 runners for testing:
test_flake8_pydocstyle:
    stage: test
    script:
        - flake8 pineboolib/
        # PyDocStyle lacks "exclude":
        - rm pineboolib/application/parsers/qsaparser/lextab.py || /bin/true
        - pydocstyle pineboolib/application pineboolib/core pineboolib/interfaces

test_mypy_pyroma_black_pytest:
    cache:
        key: "mypy-1-$CI_COMMIT_REF_SLUG"
        paths:
            - .mypy_cache/
    stage: test
    script:
        - mypy -p pineboolib
        - pyroma .
        - black --check --fast -l 100 --exclude='(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|_build|buck-out|build|dist|lextab.py)' pineboolib/
        - pytest --cov=pineboolib pineboolib/
        - coverage report --fail-under=23

deploy_build:
    stage: deploy
    script:
        - python3 setup.py bdist_wheel
        # an alternative approach is to install and run:
        - pip3 install dist/*
        # run the command here
        # pineboo --help
    artifacts:
        paths:
            - dist/*.whl

pages:
    cache:
        key: "pages-1-$CI_COMMIT_REF_SLUG"
        paths:
            - .mypy_cache/
            - docs/source/_static/linters/
            - docs/source/linters/pylint/static
            - docs/index_template.rst
            - docs/source/code/pineboolib
            - docs/build/
    stage: deploy
    script:
        # NOTE: to be able to use cache for sphinx:
        # Reset modification time of the files to the original authored time.
        - ./git_reset_mtime.sh
        - ls --full-time -lhR docs/build/
        - ls --full-time -lh pineboolib/application
        - cd docs
        - ./create_docs.sh | ts
        - ./update_linters.sh | ts
        - make html | ts
        - mv build/html/ ../public/
    artifacts:
        paths:
            - public
#   only:
#       - master
